-- Fix Team Flags - Replace emoji codes with actual emoji characters
-- This updates the teams table to have proper emoji flags instead of country codes

UPDATE teams SET flag_emoji = '🇿🇦' WHERE name = 'Afrique du Sud';
UPDATE teams SET flag_emoji = '🇩🇿' WHERE name = 'Algérie';
UPDATE teams SET flag_emoji = '🇩🇪' WHERE name = 'Allemagne';
UPDATE teams SET flag_emoji = '🇬🇧' WHERE name = 'Angleterre';
UPDATE teams SET flag_emoji = '🇸🇦' WHERE name = 'Arabie saoudite';
UPDATE teams SET flag_emoji = '🇦🇷' WHERE name = 'Argentine';
UPDATE teams SET flag_emoji = '🇦🇺' WHERE name = 'Australie';
UPDATE teams SET flag_emoji = '🇦🇹' WHERE name = 'Autriche';
UPDATE teams SET flag_emoji = '🇧🇪' WHERE name = 'Belgique';
UPDATE teams SET flag_emoji = '🇧🇦' WHERE name = 'Bosnie-Herzégovine';
UPDATE teams SET flag_emoji = '🇧🇷' WHERE name = 'Brésil';
UPDATE teams SET flag_emoji = '🇨🇦' WHERE name = 'Canada';
UPDATE teams SET flag_emoji = '🇨🇻' WHERE name = 'Cap-Vert';
UPDATE teams SET flag_emoji = '🇨🇱' WHERE name = 'Chili';
UPDATE teams SET flag_emoji = '🇨🇴' WHERE name = 'Colombie';
UPDATE teams SET flag_emoji = '🇰🇷' WHERE name = 'Corée du Sud';
UPDATE teams SET flag_emoji = '🇨🇮' WHERE name = 'Côte d''Ivoire';
UPDATE teams SET flag_emoji = '🇭🇷' WHERE name = 'Croatie';
UPDATE teams SET flag_emoji = '🇨🇼' WHERE name = 'Curaçao';
UPDATE teams SET flag_emoji = '🇪🇬' WHERE name = 'Égypte';
UPDATE teams SET flag_emoji = '🇬🇧' WHERE name = 'Écosse';
UPDATE teams SET flag_emoji = '🇪🇨' WHERE name = 'Équateur';
UPDATE teams SET flag_emoji = '🇪🇸' WHERE name = 'Espagne';
UPDATE teams SET flag_emoji = '🇺🇸' WHERE name = 'États-Unis';
UPDATE teams SET flag_emoji = '🇫🇷' WHERE name = 'France';
UPDATE teams SET flag_emoji = '🇬🇭' WHERE name = 'Ghana';
UPDATE teams SET flag_emoji = '🇭🇹' WHERE name = 'Haïti';
UPDATE teams SET flag_emoji = '🇭🇺' WHERE name = 'Hongrie';
UPDATE teams SET flag_emoji = '🇮🇶' WHERE name = 'Irak';
UPDATE teams SET flag_emoji = '🇮🇷' WHERE name = 'Iran';
UPDATE teams SET flag_emoji = '🇮🇪' WHERE name = 'Irlande';
UPDATE teams SET flag_emoji = '🇮🇸' WHERE name = 'Islande';
UPDATE teams SET flag_emoji = '🇮🇱' WHERE name = 'Israël';
UPDATE teams SET flag_emoji = '🇮🇹' WHERE name = 'Italie';
UPDATE teams SET flag_emoji = '🇯🇲' WHERE name = 'Jamaïque';
UPDATE teams SET flag_emoji = '🇯🇵' WHERE name = 'Japon';
UPDATE teams SET flag_emoji = '🇯🇴' WHERE name = 'Jordanie';
UPDATE teams SET flag_emoji = '🇰🇿' WHERE name = 'Kazakhstan';
UPDATE teams SET flag_emoji = '🇲🇼' WHERE name = 'Malawi';
UPDATE teams SET flag_emoji = '🇲🇱' WHERE name = 'Mali';
UPDATE teams SET flag_emoji = '🇲🇦' WHERE name = 'Maroc';
UPDATE teams SET flag_emoji = '🇲🇽' WHERE name = 'Mexique';
UPDATE teams SET flag_emoji = '🇲🇩' WHERE name = 'Moldavie';
UPDATE teams SET flag_emoji = '🇲🇪' WHERE name = 'Monténégro';
UPDATE teams SET flag_emoji = '🇲🇿' WHERE name = 'Mozambique';
UPDATE teams SET flag_emoji = '🇳🇵' WHERE name = 'Népal';
UPDATE teams SET flag_emoji = '🇳🇿' WHERE name = 'Nouvelle-Zélande';
UPDATE teams SET flag_emoji = '🇳🇴' WHERE name = 'Norvège';
UPDATE teams SET flag_emoji = '🇴🇲' WHERE name = 'Oman';
UPDATE teams SET flag_emoji = '🇺🇿' WHERE name = 'Ouzbékistan';
UPDATE teams SET flag_emoji = '🇵🇸' WHERE name = 'Palestine';
UPDATE teams SET flag_emoji = '🇵🇦' WHERE name = 'Panama';
UPDATE teams SET flag_emoji = '🇵🇬' WHERE name = 'Papua Nouvelle-Guinée';
UPDATE teams SET flag_emoji = '🇵🇾' WHERE name = 'Paraguay';
UPDATE teams SET flag_emoji = '🇳🇱' WHERE name = 'Pays-Bas';
UPDATE teams SET flag_emoji = '🇵🇪' WHERE name = 'Pérou';
UPDATE teams SET flag_emoji = '🇵🇭' WHERE name = 'Philippines';
UPDATE teams SET flag_emoji = '🇵🇱' WHERE name = 'Pologne';
UPDATE teams SET flag_emoji = '🇵🇫' WHERE name = 'Polynésie française';
UPDATE teams SET flag_emoji = '🇵🇷' WHERE name = 'Porto Rico';
UPDATE teams SET flag_emoji = '🇵🇹' WHERE name = 'Portugal';
UPDATE teams SET flag_emoji = '🇶🇦' WHERE name = 'Qatar';
UPDATE teams SET flag_emoji = '🇨🇩' WHERE name = 'RD Congo';
UPDATE teams SET flag_emoji = '🇨🇫' WHERE name = 'République centrafricaine';
UPDATE teams SET flag_emoji = '🇩🇴' WHERE name = 'République dominicaine';
UPDATE teams SET flag_emoji = '🇨🇬' WHERE name = 'République du Congo';
UPDATE teams SET flag_emoji = '🇨🇩' WHERE name = 'République démocratique du Congo';
UPDATE teams SET flag_emoji = '🇨🇿' WHERE name = 'République tchèque';
UPDATE teams SET flag_emoji = '🇷🇴' WHERE name = 'Roumanie';
UPDATE teams SET flag_emoji = '🇬🇧' WHERE name = 'Royaume-Uni';
UPDATE teams SET flag_emoji = '🇷🇺' WHERE name = 'Russie';
UPDATE teams SET flag_emoji = '🇷🇼' WHERE name = 'Rwanda';
UPDATE teams SET flag_emoji = '🇪🇭' WHERE name = 'Sahara occidental';
UPDATE teams SET flag_emoji = '🇸🇻' WHERE name = 'Salvador';
UPDATE teams SET flag_emoji = '🇼🇸' WHERE name = 'Samoa';
UPDATE teams SET flag_emoji = '🇦🇸' WHERE name = 'Samoa américaines';
UPDATE teams SET flag_emoji = '🇸🇲' WHERE name = 'San Marin';
UPDATE teams SET flag_emoji = '🇸🇳' WHERE name = 'Sénégal';
UPDATE teams SET flag_emoji = '🇷🇸' WHERE name = 'Serbie';
UPDATE teams SET flag_emoji = '🇸🇨' WHERE name = 'Seychelles';
UPDATE teams SET flag_emoji = '🇸🇱' WHERE name = 'Sierra Leone';
UPDATE teams SET flag_emoji = '🇸🇬' WHERE name = 'Singapour';
UPDATE teams SET flag_emoji = '🇸🇽' WHERE name = 'Sint Maarten';
UPDATE teams SET flag_emoji = '🇸🇰' WHERE name = 'Slovaquie';
UPDATE teams SET flag_emoji = '🇸🇮' WHERE name = 'Slovénie';
UPDATE teams SET flag_emoji = '🇸🇴' WHERE name = 'Somalie';
UPDATE teams SET flag_emoji = '🇸🇩' WHERE name = 'Soudan';
UPDATE teams SET flag_emoji = '🇸🇸' WHERE name = 'Soudan du Sud';
UPDATE teams SET flag_emoji = '🇱🇰' WHERE name = 'Sri Lanka';
UPDATE teams SET flag_emoji = '🇸🇪' WHERE name = 'Suède';
UPDATE teams SET flag_emoji = '🇨🇭' WHERE name = 'Suisse';
UPDATE teams SET flag_emoji = '🇸🇷' WHERE name = 'Suriname';
UPDATE teams SET flag_emoji = '🇸🇿' WHERE name = 'Swaziland';
UPDATE teams SET flag_emoji = '🇸🇾' WHERE name = 'Syrie';
UPDATE teams SET flag_emoji = '🇹🇯' WHERE name = 'Tadjikistan';
UPDATE teams SET flag_emoji = '🇵🇫' WHERE name = 'Tahiti';
UPDATE teams SET flag_emoji = '🇹🇼' WHERE name = 'Taïwan';
UPDATE teams SET flag_emoji = '🇹🇿' WHERE name = 'Tanzanie';
UPDATE teams SET flag_emoji = '🇹🇩' WHERE name = 'Tchad';
UPDATE teams SET flag_emoji = '🇹🇫' WHERE name = 'Terres australes françaises';
UPDATE teams SET flag_emoji = '🇮🇴' WHERE name = 'Territoire britannique de l''océan Indien';
UPDATE teams SET flag_emoji = '🇨🇽' WHERE name = 'Territoire des îles Christmas';
UPDATE teams SET flag_emoji = '🇨🇨' WHERE name = 'Territoire des îles Cocos';
UPDATE teams SET flag_emoji = '🇵🇫' WHERE name = 'Territoire français du Pacifique';
UPDATE teams SET flag_emoji = '🇹🇫' WHERE name = 'Territoire français du sud';
UPDATE teams SET flag_emoji = '🇫🇷' WHERE name = 'Territoire français intra-muros';
UPDATE teams SET flag_emoji = '🇹🇭' WHERE name = 'Thaïlande';
UPDATE teams SET flag_emoji = '🇹🇱' WHERE name = 'Timor oriental';
UPDATE teams SET flag_emoji = '🇹🇬' WHERE name = 'Togo';
UPDATE teams SET flag_emoji = '🇹🇰' WHERE name = 'Tokelau';
UPDATE teams SET flag_emoji = '🇹🇴' WHERE name = 'Tonga';
UPDATE teams SET flag_emoji = '🇹🇹' WHERE name = 'Trinité-et-Tobago';
UPDATE teams SET flag_emoji = '🇹🇳' WHERE name = 'Tunisie';
UPDATE teams SET flag_emoji = '🇹🇲' WHERE name = 'Turkménistan';
UPDATE teams SET flag_emoji = '🇹🇷' WHERE name = 'Turquie';
UPDATE teams SET flag_emoji = '🇹🇻' WHERE name = 'Tuvalu';
UPDATE teams SET flag_emoji = '🇺🇦' WHERE name = 'Ukraine';
UPDATE teams SET flag_emoji = '🇰🇲' WHERE name = 'Union des Comores';
UPDATE teams SET flag_emoji = '🇺🇾' WHERE name = 'Uruguay';
UPDATE teams SET flag_emoji = '🇻🇺' WHERE name = 'Vanuatu';
UPDATE teams SET flag_emoji = '🇻🇦' WHERE name = 'Vatican';
UPDATE teams SET flag_emoji = '🇻🇪' WHERE name = 'Venezuela';
UPDATE teams SET flag_emoji = '🇻🇳' WHERE name = 'Viêt Nam';
UPDATE teams SET flag_emoji = '🇼🇫' WHERE name = 'Wallis et Futuna';
UPDATE teams SET flag_emoji = '🇾🇪' WHERE name = 'Yémen';
UPDATE teams SET flag_emoji = '🇿🇲' WHERE name = 'Zambie';
UPDATE teams SET flag_emoji = '🇿🇼' WHERE name = 'Zimbabwe';

-- Verify the update
SELECT COUNT(*) as teams_with_emojis FROM teams WHERE flag_emoji LIKE '🇪' OR flag_emoji LIKE '🇺' OR flag_emoji LIKE '🇫';
