// Mapping d'URLs de drapeaux en images
// Source: flagcdn.com (libre de droits)
export const COUNTRY_FLAGS = {
  'Afrique du Sud': 'https://flagcdn.com/w40/za.png',
  'Algérie': 'https://flagcdn.com/w40/dz.png',
  'Allemagne': 'https://flagcdn.com/w40/de.png',
  'Angleterre': 'https://flagcdn.com/w40/gb.png',
  'Arabie saoudite': 'https://flagcdn.com/w40/sa.png',
  'Argentine': 'https://flagcdn.com/w40/ar.png',
  'Australie': 'https://flagcdn.com/w40/au.png',
  'Autriche': 'https://flagcdn.com/w40/at.png',
  'Belgique': 'https://flagcdn.com/w40/be.png',
  'Bosnie-Herzégovine': 'https://flagcdn.com/w40/ba.png',
  'Brésil': 'https://flagcdn.com/w40/br.png',
  'Canada': 'https://flagcdn.com/w40/ca.png',
  'Cap-Vert': 'https://flagcdn.com/w40/cv.png',
  'Chili': 'https://flagcdn.com/w40/cl.png',
  'Colombie': 'https://flagcdn.com/w40/co.png',
  'Corée du Sud': 'https://flagcdn.com/w40/kr.png',
  'Côte d\'Ivoire': 'https://flagcdn.com/w40/ci.png',
  'Croatie': 'https://flagcdn.com/w40/hr.png',
  'Curaçao': 'https://flagcdn.com/w40/cw.png',
  'Égypte': 'https://flagcdn.com/w40/eg.png',
  'Écosse': 'https://flagcdn.com/w40/gb-sct.png',
  'Équateur': 'https://flagcdn.com/w40/ec.png',
  'Espagne': 'https://flagcdn.com/w40/es.png',
  'États-Unis': 'https://flagcdn.com/w40/us.png',
  'France': 'https://flagcdn.com/w40/fr.png',
  'Ghana': 'https://flagcdn.com/w40/gh.png',
  'Haïti': 'https://flagcdn.com/w40/ht.png',
  'Hongrie': 'https://flagcdn.com/w40/hu.png',
  'Irak': 'https://flagcdn.com/w40/iq.png',
  'Iran': 'https://flagcdn.com/w40/ir.png',
  'Irlande': 'https://flagcdn.com/w40/ie.png',
  'Islande': 'https://flagcdn.com/w40/is.png',
  'Israël': 'https://flagcdn.com/w40/il.png',
  'Italie': 'https://flagcdn.com/w40/it.png',
  'Jamaïque': 'https://flagcdn.com/w40/jm.png',
  'Japon': 'https://flagcdn.com/w40/jp.png',
  'Jordanie': 'https://flagcdn.com/w40/jo.png',
  'Kazakhstan': 'https://flagcdn.com/w40/kz.png',
  'Malawi': 'https://flagcdn.com/w40/mw.png',
  'Mali': 'https://flagcdn.com/w40/ml.png',
  'Maroc': 'https://flagcdn.com/w40/ma.png',
  'Mexique': 'https://flagcdn.com/w40/mx.png',
  'Moldavie': 'https://flagcdn.com/w40/md.png',
  'Monténégro': 'https://flagcdn.com/w40/me.png',
  'Mozambique': 'https://flagcdn.com/w40/mz.png',
  'Népal': 'https://flagcdn.com/w40/np.png',
  'Nouvelle-Zélande': 'https://flagcdn.com/w40/nz.png',
  'Norvège': 'https://flagcdn.com/w40/no.png',
  'Oman': 'https://flagcdn.com/w40/om.png',
  'Ouzbékistan': 'https://flagcdn.com/w40/uz.png',
  'Palestine': 'https://flagcdn.com/w40/ps.png',
  'Panama': 'https://flagcdn.com/w40/pa.png',
  'Papua Nouvelle-Guinée': 'https://flagcdn.com/w40/pg.png',
  'Paraguay': 'https://flagcdn.com/w40/py.png',
  'Pays-Bas': 'https://flagcdn.com/w40/nl.png',
  'Pérou': 'https://flagcdn.com/w40/pe.png',
  'Philippines': 'https://flagcdn.com/w40/ph.png',
  'Pologne': 'https://flagcdn.com/w40/pl.png',
  'Polynésie française': 'https://flagcdn.com/w40/pf.png',
  'Porto Rico': 'https://flagcdn.com/w40/pr.png',
  'Portugal': 'https://flagcdn.com/w40/pt.png',
  'Qatar': 'https://flagcdn.com/w40/qa.png',
  'RD Congo': 'https://flagcdn.com/w40/cd.png',
  'République centrafricaine': 'https://flagcdn.com/w40/cf.png',
  'République dominicaine': 'https://flagcdn.com/w40/do.png',
  'République du Congo': 'https://flagcdn.com/w40/cg.png',
  'République démocratique du Congo': 'https://flagcdn.com/w40/cd.png',
  'République tchèque': 'https://flagcdn.com/w40/cz.png',
  'Roumanie': 'https://flagcdn.com/w40/ro.png',
  'Royaume-Uni': 'https://flagcdn.com/w40/gb.png',
  'Russie': 'https://flagcdn.com/w40/ru.png',
  'Rwanda': 'https://flagcdn.com/w40/rw.png',
  'Sahara occidental': 'https://flagcdn.com/w40/eh.png',
  'Salvador': 'https://flagcdn.com/w40/sv.png',
  'Samoa': 'https://flagcdn.com/w40/ws.png',
  'Samoa américaines': 'https://flagcdn.com/w40/as.png',
  'San Marin': 'https://flagcdn.com/w40/sm.png',
  'Sénégal': 'https://flagcdn.com/w40/sn.png',
  'Serbie': 'https://flagcdn.com/w40/rs.png',
  'Seychelles': 'https://flagcdn.com/w40/sc.png',
  'Sierra Leone': 'https://flagcdn.com/w40/sl.png',
  'Singapour': 'https://flagcdn.com/w40/sg.png',
  'Sint Maarten': 'https://flagcdn.com/w40/sx.png',
  'Slovaquie': 'https://flagcdn.com/w40/sk.png',
  'Slovénie': 'https://flagcdn.com/w40/si.png',
  'Somalie': 'https://flagcdn.com/w40/so.png',
  'Soudan': 'https://flagcdn.com/w40/sd.png',
  'Soudan du Sud': 'https://flagcdn.com/w40/ss.png',
  'Sri Lanka': 'https://flagcdn.com/w40/lk.png',
  'Suède': 'https://flagcdn.com/w40/se.png',
  'Suisse': 'https://flagcdn.com/w40/ch.png',
  'Suriname': 'https://flagcdn.com/w40/sr.png',
  'Swaziland': 'https://flagcdn.com/w40/sz.png',
  'Syrie': 'https://flagcdn.com/w40/sy.png',
  'Tadjikistan': 'https://flagcdn.com/w40/tj.png',
  'Tahiti': 'https://flagcdn.com/w40/pf.png',
  'Taïwan': 'https://flagcdn.com/w40/tw.png',
  'Tanzanie': 'https://flagcdn.com/w40/tz.png',
  'Tchad': 'https://flagcdn.com/w40/td.png',
  'Terres australes françaises': 'https://flagcdn.com/w40/tf.png',
  'Territoire britannique de l\'océan Indien': 'https://flagcdn.com/w40/io.png',
  'Territoire des îles Christmas': 'https://flagcdn.com/w40/cx.png',
  'Territoire des îles Cocos': 'https://flagcdn.com/w40/cc.png',
  'Thaïlande': 'https://flagcdn.com/w40/th.png',
  'Timor oriental': 'https://flagcdn.com/w40/tl.png',
  'Togo': 'https://flagcdn.com/w40/tg.png',
  'Tokelau': 'https://flagcdn.com/w40/tk.png',
  'Tonga': 'https://flagcdn.com/w40/to.png',
  'Trinité-et-Tobago': 'https://flagcdn.com/w40/tt.png',
  'Tunisie': 'https://flagcdn.com/w40/tn.png',
  'Turkménistan': 'https://flagcdn.com/w40/tm.png',
  'Turquie': 'https://flagcdn.com/w40/tr.png',
  'Tuvalu': 'https://flagcdn.com/w40/tv.png',
  'Ukraine': 'https://flagcdn.com/w40/ua.png',
  'Union des Comores': 'https://flagcdn.com/w40/km.png',
  'Uruguay': 'https://flagcdn.com/w40/uy.png',
  'Vanuatu': 'https://flagcdn.com/w40/vu.png',
  'Vatican': 'https://flagcdn.com/w40/va.png',
  'Venezuela': 'https://flagcdn.com/w40/ve.png',
  'Viêt Nam': 'https://flagcdn.com/w40/vn.png',
  'Wallis et Futuna': 'https://flagcdn.com/w40/wf.png',
  'Yémen': 'https://flagcdn.com/w40/ye.png',
  'Zambie': 'https://flagcdn.com/w40/zm.png',
  'Zimbabwe': 'https://flagcdn.com/w40/zw.png',
  'Azerbaïdjan': 'https://flagcdn.com/w40/az.png',
  'Costa Rica': 'https://flagcdn.com/w40/cr.png',
  'Albanie': 'https://flagcdn.com/w40/al.png'
};

// Retourne l'URL de l'image du drapeau
export const getFlag = (country) => {
  return COUNTRY_FLAGS[country] || null;
};
