// Mapping country names to ISO 3166-1 alpha-2 codes for react-country-flag
export const COUNTRY_CODE_MAP = {
  'Afrique du Sud': 'ZA',
  'Algérie': 'DZ',
  'Allemagne': 'DE',
  'Angleterre': 'GB',
  'Arabie saoudite': 'SA',
  'Argentine': 'AR',
  'Australie': 'AU',
  'Autriche': 'AT',
  'Belgique': 'BE',
  'Bosnie-Herzégovine': 'BA',
  'Brésil': 'BR',
  'Canada': 'CA',
  'Cap-Vert': 'CV',
  'Chili': 'CL',
  'Colombie': 'CO',
  'Corée du Sud': 'KR',
  'Côte d\'Ivoire': 'CI',
  'Croatie': 'HR',
  'Curaçao': 'CW',
  'Égypte': 'EG',
  'Écosse': 'GB',
  'Équateur': 'EC',
  'Espagne': 'ES',
  'États-Unis': 'US',
  'France': 'FR',
  'Ghana': 'GH',
  'Haïti': 'HT',
  'Hongrie': 'HU',
  'Irak': 'IQ',
  'Iran': 'IR',
  'Irlande': 'IE',
  'Islande': 'IS',
  'Israël': 'IL',
  'Italie': 'IT',
  'Jamaïque': 'JM',
  'Japon': 'JP',
  'Jordanie': 'JO',
  'Kazakhstan': 'KZ',
  'Malawi': 'MW',
  'Mali': 'ML',
  'Maroc': 'MA',
  'Mexique': 'MX',
  'Moldavie': 'MD',
  'Monténégro': 'ME',
  'Mozambique': 'MZ',
  'Népal': 'NP',
  'Nouvelle-Zélande': 'NZ',
  'Norvège': 'NO',
  'Oman': 'OM',
  'Ouzbékistan': 'UZ',
  'Palestine': 'PS',
  'Panama': 'PA',
  'Papua Nouvelle-Guinée': 'PG',
  'Paraguay': 'PY',
  'Pays-Bas': 'NL',
  'Pérou': 'PE',
  'Philippines': 'PH',
  'Pologne': 'PL',
  'Polynésie française': 'PF',
  'Porto Rico': 'PR',
  'Portugal': 'PT',
  'Qatar': 'QA',
  'RD Congo': 'CD',
  'République centrafricaine': 'CF',
  'République dominicaine': 'DO',
  'République du Congo': 'CG',
  'République démocratique du Congo': 'CD',
  'République tchèque': 'CZ',
  'Roumanie': 'RO',
  'Royaume-Uni': 'GB',
  'Russie': 'RU',
  'Rwanda': 'RW',
  'Sahara occidental': 'EH',
  'Salvador': 'SV',
  'Samoa': 'WS',
  'Samoa américaines': 'AS',
  'San Marin': 'SM',
  'Sénégal': 'SN',
  'Serbie': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapour': 'SG',
  'Sint Maarten': 'SX',
  'Slovaquie': 'SK',
  'Slovénie': 'SI',
  'Somalie': 'SO',
  'Soudan': 'SD',
  'Soudan du Sud': 'SS',
  'Sri Lanka': 'LK',
  'Suède': 'SE',
  'Suisse': 'CH',
  'Suriname': 'SR',
  'Swaziland': 'SZ',
  'Syrie': 'SY',
  'Tadjikistan': 'TJ',
  'Tahiti': 'PF',
  'Taïwan': 'TW',
  'Tanzanie': 'TZ',
  'Tchad': 'TD',
  'Terres australes françaises': 'TF',
  'Territoire britannique de l\'océan Indien': 'IO',
  'Territoire des îles Christmas': 'CX',
  'Territoire des îles Cocos': 'CC',
  'Territoire français du Pacifique': 'PF',
  'Territoire français du sud': 'TF',
  'Territoire français intra-muros': 'FR',
  'Thaïlande': 'TH',
  'Timor oriental': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinité-et-Tobago': 'TT',
  'Tunisie': 'TN',
  'Turkménistan': 'TM',
  'Turquie': 'TR',
  'Tuvalu': 'TV',
  'Ukraine': 'UA',
  'Union des Comores': 'KM',
  'Uruguay': 'UY',
  'Vanuatu': 'VU',
  'Vatican': 'VA',
  'Venezuela': 'VE',
  'Viêt Nam': 'VN',
  'Wallis et Futuna': 'WF',
  'Yémen': 'YE',
  'Zambie': 'ZM',
  'Zimbabwe': 'ZW'
};

export const getCountryCode = (country) => {
  if (!country) return 'UN'; // Default to UN flag if no country
  return COUNTRY_CODE_MAP[country] || 'UN';
};
