// Mapping des équipes vers leurs emoji drapeaux
export const COUNTRY_FLAGS = {
  'Afrique du Sud': '🇿🇦',
  'Algérie': '🇩🇿',
  'Allemagne': '🇩🇪',
  'Angleterre': '🇬🇧',
  'Arabie saoudite': '🇸🇦',
  'Argentine': '🇦🇷',
  'Australie': '🇦🇺',
  'Autriche': '🇦🇹',
  'Belgique': '🇧🇪',
  'Bosnie-Herzégovine': '🇧🇦',
  'Brésil': '🇧🇷',
  'Canada': '🇨🇦',
  'Cap-Vert': '🇨🇻',
  'Chili': '🇨🇱',
  'Colombie': '🇨🇴',
  'Corée du Sud': '🇰🇷',
  'Côte d\'Ivoire': '🇨🇮',
  'Croatie': '🇭🇷',
  'Curaçao': '🇨🇼',
  'Égypte': '🇪🇬',
  'Écosse': '🇬🇧',
  'Équateur': '🇪🇨',
  'Espagne': '🇪🇸',
  'États-Unis': '🇺🇸',
  'France': '🇫🇷',
  'Ghana': '🇬🇭',
  'Haïti': '🇭🇹',
  'Hongrie': '🇭🇺',
  'Irak': '🇮🇶',
  'Iran': '🇮🇷',
  'Irlande': '🇮🇪',
  'Islande': '🇮🇸',
  'Israël': '🇮🇱',
  'Italie': '🇮🇹',
  'Jamaïque': '🇯🇲',
  'Japon': '🇯🇵',
  'Jordanie': '🇯🇴',
  'Kazakhstan': '🇰🇿',
  'Malawi': '🇲🇼',
  'Mali': '🇲🇱',
  'Maroc': '🇲🇦',
  'Mexique': '🇲🇽',
  'Moldavie': '🇲🇩',
  'Monténégro': '🇲🇪',
  'Mozambique': '🇲🇿',
  'Népal': '🇳🇵',
  'Nouvelle-Zélande': '🇳🇿',
  'Norvège': '🇳🇴',
  'Oman': '🇴🇲',
  'Ouzbékistan': '🇺🇿',
  'Palestine': '🇵🇸',
  'Panama': '🇵🇦',
  'Papua Nouvelle-Guinée': '🇵🇬',
  'Paraguay': '🇵🇾',
  'Pays-Bas': '🇳🇱',
  'Pérou': '🇵🇪',
  'Philippines': '🇵🇭',
  'Pologne': '🇵🇱',
  'Polynésie française': '🇵🇫',
  'Porto Rico': '🇵🇷',
  'Portugal': '🇵🇹',
  'Qatar': '🇶🇦',
  'RD Congo': '🇨🇩',
  'République centrafricaine': '🇨🇫',
  'Tchéquie': '🇨🇿',
  'République dominicaine': '🇩🇴',
  'République du Congo': '🇨🇬',
  'République démocratique du Congo': '🇨🇩',
  'République Démocratique du Congo': '🇨🇩',
  'République tchèque': '🇨🇿',
  'Roumanie': '🇷🇴',
  'Royaume-Uni': '🇬🇧',
  'Russie': '🇷🇺',
  'Rwanda': '🇷🇼',
  'Sahara occidental': '🇪🇭',
  'Salvador': '🇸🇻',
  'Samoa': '🇼🇸',
  'Samoa américaines': '🇦🇸',
  'San Marin': '🇸🇲',
  'Sénégal': '🇸🇳',
  'Serbie': '🇷🇸',
  'Seychelles': '🇸🇨',
  'Sierra Leone': '🇸🇱',
  'Singapour': '🇸🇬',
  'Sint Maarten': '🇸🇽',
  'Slovaquie': '🇸🇰',
  'Slovénie': '🇸🇮',
  'Somalie': '🇸🇴',
  'Soudan': '🇸🇩',
  'Soudan du Sud': '🇸🇸',
  'Sri Lanka': '🇱🇰',
  'Suède': '🇸🇪',
  'Suisse': '🇨🇭',
  'Suriname': '🇸🇷',
  'Swaziland': '🇸🇿',
  'Syrie': '🇸🇾',
  'Tadjikistan': '🇹🇯',
  'Tahiti': '🇵🇫',
  'Taïwan': '🇹🇼',
  'Tanzanie': '🇹🇿',
  'Tchad': '🇹🇩',
  'Tchéquie': '🇨🇿',
  'Terres australes françaises': '🇹🇫',
  'Territoire britannique de l\'océan Indien': '🇮🇴',
  'Territoire des îles Christmas': '🇨🇽',
  'Territoire des îles Cocos': '🇨🇨',
  'Territoire français du Pacifique': '🇵🇫',
  'Territoire français du sud': '🇹🇫',
  'Territoire français intra-muros': '🇫🇷',
  'Thaïlande': '🇹🇭',
  'Timor oriental': '🇹🇱',
  'Togo': '🇹🇬',
  'Tokelau': '🇹🇰',
  'Tonga': '🇹🇴',
  'Trinité-et-Tobago': '🇹🇹',
  'Tunisie': '🇹🇳',
  'Turkménistan': '🇹🇲',
  'Turquie': '🇹🇷',
  'Tuvalu': '🇹🇻',
  'Ukraine': '🇺🇦',
  'Union des Comores': '🇰🇲',
  'Uruguay': '🇺🇾',
  'Vanuatu': '🇻🇺',
  'Vatican': '🇻🇦',
  'Venezuela': '🇻🇪',
  'Viêt Nam': '🇻🇳',
  'Wallis et Futuna': '🇼🇫',
  'Yémen': '🇾🇪',
  'Zambie': '🇿🇲',
  'Zimbabwe': '🇿🇼'
};

export const getCountryFlag = (country, apiFlagEmoji = null) => {
  // If flag is provided from API, use it (database is source of truth)
  if (apiFlagEmoji) return apiFlagEmoji;

  // Fallback to local mapping for backward compatibility
  return COUNTRY_FLAGS[country] || '🌍';
};
